# Generated by Django 5.0.7 on 2024-08-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Club_Name', models.CharField(max_length=50)),
                ('Club_logo', models.ImageField(upload_to='images/Clubs/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Description', models.TextField(default='', max_length=2000)),
                ('Img', models.ImageField(default='', upload_to='images/events/')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=2000)),
                ('Img', models.ImageField(default='', upload_to='images/facilities/')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='images/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('staff', 'staff'), ('council_member', 'council_member'), ('council_head', 'council_head')], default='council_member', max_length=20)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Img', models.ImageField(upload_to='images/Team/')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('EmailID', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClubTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('club_head', 'club_head'), ('club_member', 'club_member'), ('Coach', 'Coach')], default='club_member', max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Img', models.ImageField(upload_to='images/ClubTeams/')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('EmailID', models.EmailField(max_length=50)),
                ('Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
        ),
    ]
