# Generated by Django 5.0.7 on 2024-07-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
        migrations.RenameModel(
            old_name='ClubTeams',
            new_name='ClubTeam',
        ),
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryImage',
        ),
    ]
