# Generated by Django 5.0.7 on 2024-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_clubs_club_rename_clubteams_clubteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
