# Generated by Django 5.0.7 on 2024-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubteam',
            name='Role',
            field=models.CharField(choices=[('club_head', 'club_head'), ('club_member', 'club_member')], default='club_member', max_length=20),
        ),
    ]
