# Generated by Django 5.1 on 2024-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_clubteam_phonenumber_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallOfFame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Img", models.ImageField(upload_to="images/halloffame/")),
            ],
        ),
    ]
