# Generated by Django 5.0.7 on 2024-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_clubteam_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Club_logo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clubteam',
            name='Img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='Img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='Img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
